language: java
jdk:
  - oraclejdk8
env:
  - MODULE=core
  - MODULE=core/java-lib
  - MODULE=core/broadcaster
before_install:
  - cp config/settings.xml ~/.m2/settings.xml
  - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
script: cd $MODULE && mvn clean deploy
deploy:
  edge: true
  provider: cloudfoundry
  username: $CF_DEPLOY_USERNAME
  password: $CF_DEPLOY_PASSWORD
  api: https://api.run.pivotal.io
  organization: Reactivity
  space: development
  on:
    branch: issue4-sse-couchbase
    condition: $MODULE = 'core/broadcaster'